services:
  estudos_ws:
    container_name: harpia
    # if your computer uses MacOS, uncomment the line bellow
    # platform: linux/arm64
    build:    
      context: .  #Dockerfile location
    privileged: True  #Allows acess to host hardware 
    environment:
      - DISPLAY=:0 #Link the host display to container display
    volumes:  
      - ./estudos_ws/src:/root/estudos_ws/src #Links host and container files
      - /etc/localtime:/etc/localtime #Sets timezone 
      - /tmp/.X11-unix:/tmp/.X11-unix #Allows gui apps to run (Gazebo)
    network_mode: host #Share networks interface
    tty: True #Keeps container running